"""replace income source string with fk to income_sources

Revision ID: e35b4348f70c
Revises: 61539e94bed7
Create Date: 2026-05-30 21:14:43.607175

"""
import uuid
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e35b4348f70c'
down_revision: Union[str, None] = '61539e94bed7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('income_sources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('user_income_sources')

    # Seed default income sources
    income_sources_table = sa.table(
        "income_sources",
        sa.column("id", sa.UUID),
        sa.column("name", sa.String),
        sa.column("user_id", sa.UUID),
        sa.column("is_default", sa.Boolean),
    )
    op.bulk_insert(income_sources_table, [
        {"id": uuid.uuid4(), "name": "Salary", "user_id": None, "is_default": True},
        {"id": uuid.uuid4(), "name": "Freelance", "user_id": None, "is_default": True},
        {"id": uuid.uuid4(), "name": "Business", "user_id": None, "is_default": True},
        {"id": uuid.uuid4(), "name": "Investment", "user_id": None, "is_default": True},
    ])

    op.add_column('incomes', sa.Column('source_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'incomes', 'income_sources', ['source_id'], ['id'])
    op.drop_column('incomes', 'source')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incomes', sa.Column('source', sa.VARCHAR(length=30), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'incomes', type_='foreignkey')
    op.drop_column('incomes', 'source_id')
    op.create_table('user_income_sources',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_income_sources_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='user_income_sources_pkey')
    )
    op.drop_table('income_sources')
    # ### end Alembic commands ###
